### ISSUE TITLE
No issue, just to say hi.

### ISSUE THREAD

**Issue by savbran** [WickedSmoke/evolvotron#1]
Hi @WickedSmoke, I was quite absent in last months on github due to my busy work. Anyway I saw you have linked the official site of Evolvotron (the one on sourceforge) here and you updated it, very good. I'm just a java developer and not too much expert in C++ toolcain so I just made some fix to let Evolvotron to compile on my linux pc.
Anyway, I see that you are quite expert in C++ :P so is it ok for you if we keep in touch and update your repository here that is better linked to the official site and has latest stuff to compile, insted of mine?

Just for info, another source of updates is the Debian page of the Evolvotron package maintainers, they also try maintain in good condition Evolvotron. As son as I recover the link I'll put it here for reference.

Thanks /Saverio

**Comment by WickedSmoke** [comment]
Saverio, I am now the official maintainer of the project so you can open issues here or email me (the address is in the About dialog).

**Comment by WickedSmoke** [comment]
@savbran, could you change the About on your evolvotron-fixed project to not say that "upstream is not maintained anymore"?  Adding a link here would be even better.

**Comment by savbran** [comment]
sure
