### ISSUE TITLE
Proposal for binary availability

### ISSUE THREAD

**Issue by savbran** [WickedSmoke/evolvotron#2]
@WickedSmoke considering it could be very useful to avoid compiling each time Evolvotron for the most diffused systems (Windows, Linux and Mac), do you think it's possible to put also binaries on release tags, together with sources archives?
I could help to maintain aligned the binary for Linux (the easiest one I know)... what about Windows at least? Do you think Evolvotron can be compiled for it?

**Comment by savbran** [comment]
Perhaps we can evaluate to setup a little building pipeline with github?

**Comment by WickedSmoke** [comment]
The official [download site](https://sourceforge.net/projects/evolvotron/files/evolvotron/0.8/) has a zip file with the Windows x86_64 executable.  There are also links to Fedora RPMs.

The RPMs are built with the `evolvotron.spec` file.  Windows is built with a local Linux container using the `cbuild` script.  I'm not a Debian user, so I don't know if the mkdeb script still works.  I also don't have access to a Mac so someone else would have to figure out what to do there.
