### ISSUE TITLE
Trying to figure out how to build for Windows

### ISSUE THREAD

**Issue by 7trail** [WickedSmoke/evolvotron#3]
Hello,

I really apologize for putting this here. I would attempt to contact you directly, since I am unsure if this is the right place to ask for assistance, but no other places to post questions about this program were found.

I'm trying to build this on Windows. I cannot find an adequate download link for QT, nor does the build.sh appear built to build on Windows. Can you please clarify the situation?

**Comment by 7trail** [comment]
Edit- I have figured this out. I made a VM and have been working in there.

**Comment by WickedSmoke** [comment]
The archive on the SourceForge download page was built using the MinGW cross compiler in a Linux container using the `cbuild` script.  That uses a tool called `Copr` which executes the `project.b` file.

Most users will probably want to use `qmake` to build the `main.pro` project file.  I haven't installed Qt on Windows in a long while but the following link may be what you want:

    https://www.qt.io/download-qt-installer
